name: tests

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  default-python: "3.12"
  minimum-supported-python: "3.8"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]
        include:
          - os: windows-latest
            python-version: "3.12"
          - os: macos-latest
            python-version: "3.12"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Persistent .pipx_tests/package_cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.pipx_tests/package_cache/${{ matrix.python-version }}
          key: pipx-tests-package-cache-${{ runner.os }}-${{ matrix.python-version }}
      - name: Install nox
        run: python -m pip install nox
      - name: Execute Tests
        run: nox --error-on-missing-interpreters --non-interactive --session tests-${{ matrix.python-version }}
  man:
    name: Build man page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.default-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.default-python }}
          cache: "pip"
      - name: Install nox
        run: python -m pip install nox
      - name: Build man page
        run: nox --error-on-missing-interpreters --non-interactive --session build_man
      - name: Show man page
        run: man -l pipx.1

  zipapp:
    name: Build zipapp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.minimum-supported-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.minimum-supported-python }}
          cache: "pip"
      - name: Install nox
        run: pip install nox
      - name: Build zipapp
        run: nox --error-on-missing-interpreters --non-interactive --session zipapp
      - name: Test zipapp by installing black
        run: python ./pipx.pyz install black
      - uses: actions/upload-artifact@v4
        with:
          name: pipx.pyz
          path: pipx.pyz
          retention-days: 3

  binaries:
    name: Build binaries
    runs-on: ${{ matrix.job.os }}
    needs:
      - tests
    strategy:
      fail-fast: false
      matrix:
        job:
        # Linux
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-22.04
          cross: true
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-22.04
          cross: true
        - target: x86_64-unknown-linux-musl
          os: ubuntu-22.04
          cross: true
        # Windows
        - target: x86_64-pc-windows-msvc
          os: windows-2022
        # macOS
        - target: aarch64-apple-darwin
          os: macos-12
        - target: x86_64-apple-darwin
          os: macos-12

    env:
      CARGO: cargo
      CARGO_BUILD_TARGET: ${{ matrix.job.target }}
      PYAPP_REPO: pyapp
      PYAPP_VERSION: "0.14.0"
      PYAPP_PIP_EXTERNAL: "true"
      PYAPP_PASS_LOCATION: "true"

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Fetch PyApp
        run: >-
          mkdir $PYAPP_REPO && curl -L
          https://github.com/ofek/pyapp/releases/download/v$PYAPP_VERSION/source.tar.gz
          |
          tar --strip-components=1 -xzf - -C $PYAPP_REPO
      
      - name: Set up Python ${{ env.default-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.default-python }}
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: Set up cross compiling
        if: matrix.job.cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      
      - name: Build
        run: nox --error-on-missing-interpreters --non-interactive --session build

      - name: Configure cross compiling
        if: matrix.job.cross
        run: echo "CARGO=cross" >> $GITHUB_ENV

      - name: Configure target
        run: |-
          config_file="$PYAPP_REPO/.cargo/config_${{ matrix.job.target }}.toml"
          if [[ -f "$config_file" ]]; then
            mv "$config_file" "$PYAPP_REPO/.cargo/config.toml"
          fi
      
      - name: Configure embedded project
        if: ${{ !startsWith(github.event.ref, 'refs/tags') }}
        run: |-
          cd dist
          wheel="$(echo *.whl)"
          mv "$wheel" "../$PYAPP_REPO"
          echo "PYAPP_PROJECT_PATH=$wheel" >> $GITHUB_ENV


      - name: Build binary
        run: hatch build --target app

      - name: Archive binary
        run: |-
          mkdir packaging
          cd dist/app

          binary="$(ls)"

          if [[ "$binary" =~ -pc-windows- ]]; then
            7z a "../../packaging/${binary:0:-4}.zip" "$binary"
          else
            chmod +x "$binary"
            tar -czf "../../packaging/$binary.tar.gz" "$binary"
          fi
      
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: staged-${{ runner.os }}
          path: packaging/*
          if-no-files-found: error
          retention-days: 3

  pypi-publish:
    name: Publish pipx to PyPI on release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [tests, man, zipapp]
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pipx
    permissions:
      id-token: write
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.default-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.default-python }}
          cache: "pip"
      - name: Install nox
        run: pip install nox
      - name: Build sdist and wheel
        run: nox --error-on-missing-interpreters --non-interactive --session build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@v1.8.11

  upload-zipapp:
    name: Upload zipapp to GitHub Release on release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [tests, man, zipapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pipx.pyz
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: pipx.pyz

  bump-changelog:
    name: Bump changelog on release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [pypi-publish, upload-zipapp]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.default-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.default-python }}
          cache: "pip"
      - name: Extract release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create pull request branch
        run: git switch -c "bump-changelog-for-${RELEASE_VERSION}"
      - name: Install nox
        run: python -m pip install nox
      - name: Update changelog
        run: nox --error-on-missing-interpreters --non-interactive --session build_changelog -- $RELEASE_VERSION
      - name: Commit and push change
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Bump changelog for $RELEASE_VERSION"
          git push origin "bump-changelog-for-${RELEASE_VERSION}"
      - name: Create pull request
        run: |
          git fetch origin
          gh pr create --base main --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
